/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui2;

import entity.Shop;
import entity.Shoes;
import entity.Client;
import interfaces.Keeping;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.ItemSelectable;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.event.ListDataListener;
import keeper.BaseKeeper;

public class GuiApp2 extends javax.swing.JFrame {
  private Keeping keeper = new BaseKeeper();
  private List<Shoes> shoes;
  private List<Client> clients;
  private JPanelClient jPanelClient;
  
  /**
   * Creates new form GuiApp2
   */
  public GuiApp2() {
    shoes = keeper.loadShoes();
    clients = keeper.loadClient();
    ComboBoxModel clientListModel = getClientListModel();
    if(clientListModel.getSize()!= 0){
      jComboBoxClient.setModel(clientListModel);
      jComboBoxClient.setRenderer(createListClientRenderer());
      jComboBoxClient.addItemListener(itemListener);
    }
    ListModel shoesListModel = getShoesListModel();
    if(shoesListModel.getSize() != 0){
      //jListBooks.setModel(getBooksListModel());
     // jListShoes.setCellRenderer(createListBooksRenderer());
    }

    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list3 = new java.awt.List();
        jPanelGeneral = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        labelClient = new java.awt.Label();
        btnClient = new javax.swing.JButton();
        btnManager = new javax.swing.JButton();
        btnDirctor = new javax.swing.JButton();
        jComboBoxClient = new javax.swing.JComboBox<>();
        panelCardMain = new java.awt.Panel();
        cardDirector = new java.awt.Panel();
        labelManager = new java.awt.Label();
        jTextFieldAccount = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        //jLabelLastName = new javax.swing.JLabel();
        //jTextFieldLastName = new javax.swing.JTextField();
        
        jLabelAccount = new javax.swing.JLabel();
        //jTextFieldAccount = new javax.swing.JTextField();
        jButtonAddClient = new javax.swing.JButton();
        cardClient = new java.awt.Panel();
        
        jLabelShoes = new javax.swing.JLabel();
        jButtonTakeOutShoes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListShoes = new javax.swing.JList<>();
        cardManager = new java.awt.Panel();
        jButtonAddShoes = new javax.swing.JButton();
        JTextFieldShoesName = new javax.swing.JTextField();
        jLabelShoesName = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        JTextFieldPrice = new javax.swing.JTextField();
        jLabelQuantity = new javax.swing.JLabel();
        JTextFieldQuantity = new javax.swing.JTextField();
        //jLabelAuthors = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        setMaximumSize(new java.awt.Dimension(480, 290));
        setMinimumSize(new java.awt.Dimension(480, 290));

        jPanelGeneral.setMaximumSize(new java.awt.Dimension(480, 290));
        jPanelGeneral.setMinimumSize(new java.awt.Dimension(480, 290));
        jPanelGeneral.setPreferredSize(new java.awt.Dimension(480, 290));

        jLabelTitle.setText("Выберите свою роль");

        labelClient.setText("Выберите себя");

        btnClient.setText("Client");
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });

        btnManager.setText("Manager");
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });

        btnDirctor.setText("Director");
        btnDirctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirctorActionPerformed(evt);
            }
        });

        panelCardMain.setMaximumSize(new java.awt.Dimension(480, 290));
        panelCardMain.setPreferredSize(new java.awt.Dimension(480, 290));
        panelCardMain.setLayout(new java.awt.CardLayout());

        cardDirector.setMaximumSize(new java.awt.Dimension(480, 290));
        cardDirector.setMinimumSize(new java.awt.Dimension(480, 90));
        cardDirector.setPreferredSize(new java.awt.Dimension(480, 290));

        labelManager.setText("Заполните форму");

        jLabelName.setText("Имя");
        jLabelName.setName("Имя"); // NOI18N
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
/*
        jLabelLastName.setText("Фамилия");

        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });
        */

        jLabelAccount.setText("Номер счета");
        
        jTextFieldAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        
        jButtonAddClient.setText("Добавить клиента");
        jButtonAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardDirectorLayout = new javax.swing.GroupLayout(cardDirector);
        cardDirector.setLayout(cardDirectorLayout);
        cardDirectorLayout.setHorizontalGroup(
            cardDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDirectorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardDirectorLayout.createSequentialGroup()
                        .addGroup(cardDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cardDirectorLayout.createSequentialGroup()
                                .addGroup(cardDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    //.addComponent(jLabelLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(jLabelAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cardDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    //.addComponent(jTextFieldLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAddClient, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardDirectorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))))
        );
        cardDirectorLayout.setVerticalGroup(
            cardDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDirectorLayout.createSequentialGroup()
                .addComponent(labelManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cardDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardDirectorLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardDirectorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                /*.addGroup(cardDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLastName)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)*/
                .addGroup(cardDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddClient)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        labelManager.getAccessibleContext().setAccessibleName("Выберите менеджера");
        jLabelName.getAccessibleContext().setAccessibleName("");

        panelCardMain.add(cardDirector, "cardDirector");

        jLabelShoes.setText("Выбери товар");

        jButtonTakeOutShoes.setText("Нажми, чтобы купить");
        jButtonTakeOutShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTakeOutShoesActionPerformed(evt);
            }
        });

        jListShoes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListShoes);

        javax.swing.GroupLayout cardClientLayout = new javax.swing.GroupLayout(cardClient);
        cardClient.setLayout(cardClientLayout);
        cardClientLayout.setHorizontalGroup(cardClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardClientLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonTakeOutShoes)
                .addGap(25, 25, 25))
            .addGroup(cardClientLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(cardClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelShoes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        cardClientLayout.setVerticalGroup(cardClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelShoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTakeOutShoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCardMain.add(cardClient, "cardClient");

        jButtonAddShoes.setText("Добавить товар");
        jButtonAddShoes.setActionCommand("");

        JTextFieldShoesName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldShoesNameActionPerformed(evt);
            }
        });

        jLabelShoesName.setText("Название");

        jLabelPrice.setText("Стоимость");

        JTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldPriceActionPerformed(evt);
            }
        });

        jLabelQuantity.setText("Количество");

        JTextFieldQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldQuantityActionPerformed(evt);
            }
        });

        //jLabelAuthors.setText("Авторы");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout cardManagerLayout = new javax.swing.GroupLayout(cardManager);
        cardManager.setLayout(cardManagerLayout);
        cardManagerLayout.setHorizontalGroup(
            cardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardManagerLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(cardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAddShoes, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardManagerLayout.createSequentialGroup()
                        .addComponent(jLabelPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardManagerLayout.createSequentialGroup()
                        .addComponent(jLabelShoesName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldShoesName, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardManagerLayout.createSequentialGroup()
                        .addGroup(cardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelQuantity))
                            //.addComponent(jLabelAuthors))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTextFieldQuantity)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        cardManagerLayout.setVerticalGroup(
            cardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldShoesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelShoesName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                /*.addGroup(cardManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAuthors)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)*/
                .addComponent(jButtonAddShoes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelCardMain.add(cardManager, "cardManager");

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabelTitle))
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDirctor))
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxClient, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(481, 481, 481)
                .addComponent(panelCardMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(10, 10, 10)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClient)
                    .addComponent(btnManager)
                    .addComponent(btnDirctor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(panelCardMain, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelClient.getAccessibleContext().setAccessibleName("Client");
        panelCardMain.getAccessibleContext().setAccessibleName("cardMain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaderActionPerformed
    CardLayout card = (CardLayout) panelCardMain.getLayout();
    card.show(panelCardMain, "card2");
//    if(jPanelClient == null){
//      jPanelClient = new JPanelReader();
//    }
//    this.setContentPane(jPanelClient);
//    jPanelClient.setVisible(true);
  }//GEN-LAST:event_btnReaderActionPerformed

  private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
    CardLayout card = (CardLayout) panelCardMain.getLayout();
    card.show(panelCardMain, "card3");
  }//GEN-LAST:event_btnManagerActionPerformed

  private void btnDirctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirctorActionPerformed
    CardLayout card = (CardLayout) panelCardMain.getLayout();
    card.show(panelCardMain, "card4");
  }//GEN-LAST:event_btnDirctorActionPerformed

  private void jButtonTakeOutShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTakeOutBookActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonTakeOutBookActionPerformed

  private void JTextFieldShoesNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldBookNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_JTextFieldBookNameActionPerformed

  private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldLastNameActionPerformed

  private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldFirstNameActionPerformed

  private void jButtonAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddReaderActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonAddReaderActionPerformed

  private void JTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldPublishedYearActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_JTextFieldPublishedYearActionPerformed

  private void JTextFieldQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldQuantityActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_JTextFieldQuantityActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GuiApp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GuiApp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GuiApp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GuiApp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GuiApp2().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldShoesName;
    private javax.swing.JTextField JTextFieldPrice;
    private javax.swing.JTextField JTextFieldQuantity;
    private javax.swing.JButton btnDirctor;
    private javax.swing.JButton btnManager;
    private javax.swing.JButton btnClient;
    private java.awt.Panel cardDirector;
    private java.awt.Panel cardManager;
    private java.awt.Panel cardClient;
    private javax.swing.JButton jButtonAddShoes;
    private javax.swing.JButton jButtonAddClient;
    private javax.swing.JButton jButtonTakeOutShoes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<Client> jComboBoxClient;
    //private javax.swing.JLabel jLabelAuthors;
    private javax.swing.JLabel jLabelShoesName;
    private javax.swing.JLabel jLabelShoes;
    private javax.swing.JLabel jLabelName;
    //private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelAccount;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jListShoes;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldName;
    //private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldAccount;
    private java.awt.Label labelManager;
    private java.awt.Label labelClient;
    private java.awt.List list3;
    private java.awt.Panel panelCardMain;
    // End of variables declaration//GEN-END:variables
  private ListCellRenderer<? super Client> createListClientRenderer(){
      return new DefaultListCellRenderer(){
          private final Color background = new Color(0, 100, 255, 15);
          private final Color defaultBackground = (Color) UIManager.get("List.background");
          @Override
          public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                                                        boolean isSelected, boolean cellHasFocus) {
              Component component = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
              if (component instanceof JLabel) {
                  JLabel label = (JLabel) component;
                  Client client = (Client) value;
                  label.setText(String.format("%d. %s. %s. Телефон: %s%n"
                          ,client.getId()
                          ,client.getName()
                          ,client.getAccount()
                          ,client.getMoney()
                  ));
                  if (!isSelected) {
                      label.setBackground(index % 2 == 0 ? background : defaultBackground);
                  }
              }
              return component;
          }
      };
  }
  
  ItemListener itemListener = new ItemListener() {
      @Override
      public void itemStateChanged(ItemEvent itemEvent) {
        int state = itemEvent.getStateChange();
        System.out.println((state == ItemEvent.SELECTED) ? "Selected" : "Deselected");
        System.out.println("Item: " + itemEvent.getItem());
        ItemSelectable is = itemEvent.getItemSelectable();
        
      }

        
  };
  private ListModel<Shoes> getShoesListModel(){
    DefaultListModel<Shoes> models = new DefaultListModel<>();
    for(Shoes shoe: shoes){
      models.addElement(shoe);
    }
    return models;
  } 
  private ComboBoxModel<Client> getClientListModel(){
    DefaultComboBoxModel<Client> models = new DefaultComboBoxModel<Client>();
    for(Client client:clients){
      models.addElement(client);
    }
    return models;
  }
  private ListCellRenderer<? super Shoes> createListShoesRenderer() {
    return new DefaultListCellRenderer(){
        private final Color background = new Color(0, 100, 255, 15);
        private final Color defaultBackground = (Color) UIManager.get("List.background");

        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                                                      boolean isSelected, boolean cellHasFocus) {
            Component component = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (component instanceof JLabel) {
                JLabel label = (JLabel) component;
                Shoes shoes = (Shoes) value;
                label.setText(String.format("%d. %s. %d. В наличии: %d%n"
                        ,shoes.getId()
                        ,shoes.getName()
                        
                        ,shoes.getPrice()
                        ,shoes.getQuantity()
                ));
                if (!isSelected) {
                    label.setBackground(index % 2 == 0 ? background : defaultBackground);
                }
            }
            return component;
        }
        
    };
  }
    
}
